DROP DATABASE IF EXISTS keenbo;
CREATE DATABASE keenbo;
USE keenbo;

CREATE TABLE users (
  username VARCHAR(100) PRIMARY KEY,
  password TEXT NOT NULL ,
  name TEXT NOT NULL ,
  email TEXT NOT NULL ,
  token TEXT NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE clicks (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  destination VARCHAR(2048) NOT NULL,
  label INT(1) NOT NULL,
  FOREIGN KEY (username) REFERENCES users(username)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE searches (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  text TEXT NOT NULL,
  FOREIGN KEY (username) REFERENCES users(username)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
